--- a/Makefile  2019-04-18 01:34:59.815959728 -0000
+++ b/Makefile  2019-04-18 01:32:26.312322038 -0000
@@ -117,9 +117,6 @@

 -include comp_opts.mk

-$(BINDIR)/lfe%:
-	$(INSTALL_BIN) $@ $(DESTBINDIR)
-
 install: compile install-man
	rm -Rf $(DESTEBINDIR)
	$(INSTALL_DIR) $(DESTEBINDIR)
@@ -127,7 +124,13 @@
	$(INSTALL_DATA) $(addprefix $(EBINDIR)/, $(EBINS)) $(DESTEBINDIR)
	$(INSTALL_DATA) $(addprefix $(EBINDIR)/, $(LBINS)) $(DESTEBINDIR)
	$(INSTALL_DIR) $(DESTBINDIR)
-	$(MAKE) $(BINDIR)/lfe $(BINDIR)/lfec $(BINDIR)/lfedoc $(BINDIR)/lfescript
+	$(INSTALL_BIN) \
+		$(BINDIR)/lfe \
+		$(BINDIR)/lfec \
+		$(BINDIR)/lfedoc \
+		$(BINDIR)/lfescript \
+		$(BINDIR)/lfeexec \
+		$(DESTBINDIR)
	ln -sf $(DESTBINDIR)/* $(PREFIX)/bin/

 clean:
